gui:
  border: rounded # Customize the border for a cleaner look
  nerdFontsVersion: "3" # Enable icons and smoother graph lines
git:
  log:
    showGraph: always # Always show commit graph
  pagers:
    - colorArg: always # Use colors always
      pager: delta --paging=never # use delta and disable internal paging
  parseEmoji: true # Display emojis in commit messages
  overrideGpg: true # Enable git commit reword when using gpg tools such as 1Password
