os:
  editPreset: "nvim"
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
  # Enable git commit reword when using gpg tools such as 1Password
  overrideGpg: true
# This ensures LazyGit uses the 'nvim-remote' logic
# so it doesn't open a "Neovim inside a Neovim"
core:
  editor: "nvim"
