os:
  editPreset: "nvim"
git:
  # Use delta as the preferred pager
  pagers:
    - colorArg: always
      pager: delta --paging=never
  paging:
    pager: delta
  # Enable git commit reword when using gpg tools such as 1Password
  overrideGpg: true
# This ensures LazyGit uses the 'nvim-remote' logic
# so it doesn't open a "Neovim inside a Neovim"
core:
  editor: "nvim"
